# Site settings
title: Issam Ben Blog
description: My blog description
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samben00.github.io/issam-blog"

# User settings
username: Issam Ben
user_description: Software Engineere
user_title: Full Stack Developer
email: i.bensirhir@gmail.com
#twitter_username: lorem_ipsum
#github_username:  lorem_ipsum
#gplus_username:  lorem_ipsum
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
