# Site settings
title: Issam Ben Blog
description: ISSAM BEN BLOG - Tutorials about different different technologies and cool programming stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://3issamben.github.io/issam-blog"

# User settings
username: Issam Ben
user_description: Software Engineer
user_title: Software Engineer
email: bensirhir.issam@gmail.com
#twitter_username: lorem_ipsum
#github_username:  lorem_ipsum
#gplus_username:  lorem_ipsum
disqus_username: issamben-com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
future: true


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
